name: NPM publish CD workflow

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run test -- --coverage --watchAll=false
          
      - name: npm publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm run trypublish
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
