name: NPM publish CD workflow

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run test -- --coverage --watchAll=false

      - name: Setup GIT
      - run: |
          git reset --hard
          git config --local --list
          git checkout master
          git config user.email "$GH_EMAIL"
          git config user.name "lexnim"
        env:
            GH_EMAIL: ${{secrets.GH_EMAIL}}
          
      - name: Bump version
      - run: |
          git reset --hard
          npm version patch
          npm run build
          git add . || true
          git commit -m "Build update" || true
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      - name: npm publish
      - run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
